print("Program starting.")
print("Estimate how many minutes you spent on programming...")
print()
T1 = int(input("A1_T1: "))
T2 = int(input("A1_T2: "))
T3 = int(input("A1_T3: "))
T4 = int(input("A1_T4: "))
T5 = int(input("A1_T5: "))
T6 = int(input("A1_T6: "))
T7 = int(input("A1_T7: "))
total = T1 + T2 + T3 + T4 + T5 + T6 + T7
average = total / 7
print()
print(f"In total you spent {total} minutes on programming.\nAverage per task was {round(average, 2)} min and the same rounded to the nearest integer is {round(average)} min.")
print()
print("Program ending.")
